language: php
php:
  - 5.4
script: ./vendor/bin/phpunit test
before_script:
  - pear channel-discover pear.apache.org/log4php
  - pear install log4php/Apache_log4php
  - composer self-update
  - composer install

